global:
  xraylab:
    namespace: xraylab-1
    s3:
      bucketSource: ""
      bucketBaseName: ""
  datacenter:
    clustername: ""
    region: ""

#md2.0 scaffolding for values
#https://github.com/red-hat-data-services/jumpstart-library/blob/main/demo1-xray-pipeline/manual_deployment/deployment/02_config-maps.yaml
#From jumpstart-library
images:
  bucketSource: xray-source
  bucketBaseName: xray-source
#

#ImageStream values:
imageStream:
  tags:
    name: latest
  from:
    name: "quay.io/rh-data-services/xraylab-image-generator:latest"  

#The following RBAC section is just scaffolding in case you wanted to create your own RBAC policies
rbac:
  roles:
    - name: "" # Role Name 
      createRole: false #Set to true if you want to create a role
      apiGroups:
        - "" #Provide your api group ('""' for core api (i.e. secrets) )
      scope:
        cluster: true #Is this role a cluster or namespaced role
        namespace: #If the scope is namespaced, provide the namespace to create the role in
      resources: 
        - "" #Provide the resources (i.e. secrets, configmaps )
      verbs:
        - "get"
        - "list"
        - "watch"
  roleBindings:
    - name: "" #Name of the rolebinding
      createBinding: false #Set to true if you want to create a rolebinding
      scope:
        cluster: true #Is this rolebinding to a clusterRole or a namespaced role (kind: Role) - Set to False for namespaced role.
        namespace: "" #If the scope is namespaced, provide the namespace to create the rolebinding in
      subjects:
        kind: ServiceAccount
        name: "" #Provide the name of the serviceaccount to use
        namespace: "" #Provide the namespace where the service account is created
        apiGroup: ""
      roleRef:
        kind: ClusterRole # or Role depending on the type of role created
        name: "" #Provide the name of the Role/ClusterRole to associate with this binding