global:
  namespace: ml

kubeflow:
  repos:
    - name: kf-manifests
      uri: https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    - name: manifests
      uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.2
