apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.app }}
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.kafka.app }}
  replicas: {{ .Values.kafka.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.app }}
    spec:
      containers:
        - name: {{ .Values.kafka.app }}
          image: {{ .Values.kafka.deployment.image }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
          env:
          {{- range .Values.kafka.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
