apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20"
  name: create-s3-secret
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=complete job/job-odf-storagecluster-complete --timeout=600s
          '/tmp/create-s3-secret.sh'
        name: create-s3-secret
        volumeMounts:
          - mountPath: /tmp/create-s3-secret.sh
            name: create-s3-secret
            subPath: create-s3-secret.sh
      volumes:
        - name: create-s3-secret
          configMap:
            name: create-s3-secret
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 400
