apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: xray-images
  namespace: {{ .Values.global.xraylab.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.global.xraylab.kafka.cluster.name }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
