apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: openshift-storage
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  awsS3:
    region: {{ .Values.global.datacenter.region }}
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage
    targetBucket: {{ .Values.global.xraylab.ocsstorage.targetBucket }}
  type: aws-s3
status: {}
