kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.database.name }}
  namespace: "{{ .Values.global.xraylab.namespace }}"
  labels:
    app: {{ .Values.database.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 3
  test: false
  selector:
    app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: mariadb
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-user
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-db
            - name: MYSQL_MASTER_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-master-user
            - name: MYSQL_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-master-password
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: xraylabdb-data
              mountPath: /var/lib/mysql/data
            - name: xraylabdb-init
              mountPath: /opt/app-root/src/mysql-init/90-init-data.sh
              subPath: 90-init-data.sh
            - mountPath: /opt/app-root/src/mysql-data/import.sql
              name: xraylabdb-init
              subPath: import.sql
            - name: xraylabdb-init
              mountPath: /opt/app-root/src/mysql-data/schema.sql
              subPath: schema.sql
          terminationMessagePolicy: File
          image: {{ .Values.database.image }}
      volumes:
      - configMap:
          defaultMode: 420
          name: xraylabdb-init
        name: xraylabdb-init
      - name: xraylabdb-data
        persistentVolumeClaim:
          claimName: {{ .Values.database.name }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
