global:
  xraylab:
    namespace: xraylab-1
    s3:
      bucketBaseName: ""
  datacenter:
    storageClassName: gp2
    region: ""

objectStore:
  user: 
    name: xraylab-1
    displayName: "XRaylab-1 RGW User"
  name: ocs-storagecluster-cephobjectstore
  namespace: openshift-storage

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

kafkaSource:
  bootstrapserver: "xray-cluster-kafka-bootstrap.xraylab-1.svc:9092"
  name: "xray-images"
  consumerGroup: "risk-assessment"

imageStream:
  tags:
    name: latest
  from:
    name: "quay.io/rh-data-services/xraylab-risk-assessment:latest"

rbac:
  roles:
    - name: view-odf-storageclusters
      createRole: true
      apiGroups:
        - "ocs.openshift.io"
      scope:
        cluster: true
      resources: 
        - storageclusters
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: view-odf-cephobjectstores
      createRole: true
      apiGroups:
        - "ceph.rook.io"
      scope:
        cluster: true
      resources:
        - cephobjectstores
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: view-odf-objectstoreusers
      createRole: true
      apiGroups:
        - "ceph.rook.io"
      scope:
        cluster: true
      resources:
        - cephobjectstoreusers
      verbs:
        - "get"
        - "list"
        - "watch"
    - name: read-objectstore-secret
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - secrets
      verbs:
        - '"get"'
        - '"list"'
        - '"watch"'
    - name: create-pattern-secret
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: false
        namespace: xraylab-1
      resources:
        - '"secrets"'
      verbs:
        - '"create"'
        - '"watch"'
        - '"update"'
        - '"patch"'
        - '"delete"'
    - name: view-pattern-jobs
      createRole: true
      apiGroups:
        - batch
      scope:
        cluster: false
        namespace: xraylab-1
      resources:
        - '"jobs"'
      verbs:
        - '"get"'
        - '"list"'
        - '"watch"'
  roleBindings:
    - name: read-objectstore-secret
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: read-objectstore-secret
    - name: create-pattern-secret
      createBinding: true
      scope:
        cluster: false
        namespace: xraylab-1
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: Role
        name: create-pattern-secret
    - name: view-odf-storageclusters
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-storageclusters
    - name: view-odf-cephobjectstores
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-cephobjectstores
    - name: view-odf-objectstoreusers
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-odf-objectstoreusers
    - name: view-pattern-jobs
      createBinding: true
      scope:
        cluster: false
        namespace: xraylab-1
      subjects:
        kind: ServiceAccount
        name: xraylab-1-sa
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: Role
        name: view-pattern-jobs