apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "16"
  name: job-riskassessment-wait-for-rgw-bucket-init
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=complete job/bucket-init --timeout=1200s
        name: riskassessment-wait-for-rgw-bucket-init
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      activeDeadlineSeconds: 1200
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 60
